keys:
  - &users:
      - &marrero D1912EEBC3FBEBB4
  - &hosts:
    - &hadron age1vwaq7aurp2t4dvkx4sh7psl9lkm0dlfcc9gpm5rze7fna5epsyjqg4ueew
    - &lepton age107g59gysry37u5cay3ylcj7qndqhcecvpvhxdpxsxd6z9dycrguqlvddgm
creation_rules:
  - path_regex: hosts/hadron/secrets.yaml$
    key_groups:
      - age:
        - *hadron
        pgp:
        - *marrero
  - path_regex: hosts/lepton/secrets.yaml$
    key_groups:
      - age:
        - *lepton
        pgp:
        - *marrero
