keys:
  - &users:
      - &marrero D1912EEBC3FBEBB4
  - &hosts:
    - &hadron age14v0pler7zgmuqr80usy72vztc3yxt4sgnmm3v6qj7ajv7gf4wdcqwfn590
    - &ntb age139uawl46z2thc9y5h4jemcx37jxhn3xx24lkvrdappyy4neard0qjku2e5    
creation_rules:
  - path_regex: hosts/hadron/secrets.yaml$
    key_groups:
      - age:
        - *hadron
        pgp:
        - *marrero
  - path_regex: hosts/ntb/secrets.yaml$
    key_groups:
      - age:
        - *ntb
        pgp:
        - *marrero
