keys:
  - &users:
      - &marrero D1912EEBC3FBEBB4
  - &hosts:
    - &workstation age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
    - &ntb age139uawl46z2thc9y5h4jemcx37jxhn3xx24lkvrdappyy4neard0qjku2e5    
creation_rules:
  - path_regex: hosts/workstation/secrets.yaml$
    key_groups:
      - age:
        - *workstation
        pgp:
        - *marrero
  - path_regex: hosts/ntb/secrets.yaml$
    key_groups:
      - age:
        - *ntb
        pgp:
        - *marrero
