keys:
  - &users:
      - &marrero D1912EEBC3FBEBB4
  - &hosts:
    - &workstation age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
    - &lepton age177etrm4t59vtagmenpdf8tdv5wgvt8qdh8f3rhya5w94lzy6mq9s828wfn
creation_rules:
  - path_regex: hosts/workstation/secrets.yaml$
    key_groups:
      - age:
        - *workstation
        pgp:
        - *marrero
  - path_regex: hosts/lepton/secrets.yaml$
    key_groups:
      - age:
        - *lepton
        pgp:
        - *marrero
