keys:
  - &users:
      - &marrero D1912EEBC3FBEBB4
  - &hosts:
    - &hadron age14v0pler7zgmuqr80usy72vztc3yxt4sgnmm3v6qj7ajv7gf4wdcqwfn590
    - &lepton age1av4y9te3g9qpfd2cltx6v52txm29z30y20cl2ddksd82ucnw8pjqcvemz8
creation_rules:
  - path_regex: hosts/hadron/secrets.yaml$
    key_groups:
      - age:
        - *hadron
        pgp:
        - *marrero
  - path_regex: hosts/lepton/secrets.yaml$
    key_groups:
      - age:
        - *lepton
        pgp:
        - *marrero
