# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/54b96458-f046-473b-b281-88bfa565f148";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/c54c60e2-63e2-4a4a-a247-d1e66d6664bd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E189-0B67";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c02cf47-66c3-44ba-acd8-afe5a4b15f12"; }
    ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    pulseaudio.enable = false;
    bluetooth.enable = false;

    opengl = {
      enable = true;
      extraPackages = with pkgs; [
        vulkan-validation-layers
      ];
    };
  };
}
