name: Nix Flake Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  nix-flake-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run nix flake update
        run: |
          nix flake update

      - name: Check if there are changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit changes
        run: |
          if git diff --exit-code; then
            echo "No changes to commit"
          else
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@users.noreply.github.com"
            git add .
            git commit -m "Automated nix flake update"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
